v0.5
Preferences! XZone will now remember the options you choose when you
first run it and won’t ask again! And when you quit the script, it
allows you to restart from where you left off with no problems! Yay!

diff --git a/xzone b/xzone
--- a/xzone
+++ b/xzone
@@ -3,18 +3,22 @@
 #
 #		#############################################################
 #		#															#
-#		#	XZone Bash Script 0.4 - Verbose - Scytheri0n			#
+#		#					XZone 0.5 - Scytheri0n					#
 #		#															#
-#		#	A simple bash script to create a HomePass network		#
-#		#	on OS X.												#
+#		#	A simple command line utility to create a HomePass		#
+#		#					network on OS X.						#
 #		#															#
 #		#############################################################
 #
 #	Changelog:
 #
+#	0.5		-	Preferences! XZone will now save user choices into a .plist and recall
+#				them at next start. Fixed a little bug with the SSID array. Improved 
+#				getting input from user on first run.
+#
 #	0.4		-	Improved Nintendo World function to ensure that "attwifi" SSID is used. 
 #				Added SSIDs to allow for selecting SSID to spoof at start. Backs up
-#				current IS config to allow user to revert on exit.
+#				current IS config and MAC to allow user to revert on exit.
 #
 #	0.3		-	Corrected script to not mistakenly warn that 2 minutes is too low
 #				a cycle rate as well as corrected skipping of "ff" MAC. Included Nintendo #				World MACs. Allowed starting from custom MAC increment. Cleaned up script.
@@ -58,26 +62,26 @@ originalMAC=$(networksetup -getmacaddress Wi-Fi | awk '{print $3}')
 ########################################################################################
 
 #	AT&T WiFi Services
-ssid[01]="61747477696669"									#	attwifi
-ssid[02]="4d63446f6e616c647320467265652057694669"			#	McDonalds Free WiFi
+ssid[1]="61747477696669"									#	attwifi
+ssid[2]="4d63446f6e616c647320467265652057694669"			#	McDonalds Free WiFi
 
 #	McDonald's Germany
-ssid[03]="4e5a404d634431"									#	NZ@McD1
-ssid[04]="4e5a404d634432"									#	NZ@McD2
+ssid[3]="4e5a404d634431"									#	NZ@McD1
+ssid[4]="4e5a404d634432"									#	NZ@McD2
 
 #	Wifine
-ssid[05]="776966696e65"										#	wifine
+ssid[5]="776966696e65"										#	wifine
 
 #	FreeSpot
-ssid[06]="4652454553504f54"									#	FREESPOT
+ssid[6]="4652454553504f54"									#	FREESPOT
 
 
 #	NOA Internal
-ssid[07]="6e6f6173703031"									#	noasp1
-ssid[08]="6e6f6173703032"									#	noasp2
+ssid[7]="6e6f6173703031"									#	noasp1
+ssid[8]="6e6f6173703032"									#	noasp2
 
 #	Boingo Wireless
-ssid[09]="426f696e676f20486f7473706f74"						#	Boingo Hotspot
+ssid[9]="426f696e676f20486f7473706f74"						#	Boingo Hotspot
 ssid[10]="626f696e676f20686f7473706f74"						#	boingo hotspot
 ssid[11]="41544c2d57692d4669"								#	ATL-Wi-Fi
 ssid[12]="546f726f6e746f2050656172736f6e2057692d4669"		#	Toronto Pearson Wi-Fi
@@ -160,9 +164,9 @@ function testForHex {					#	Makes sure $startPoint is a valid octet
         printf "Starting at "$MAC$endHex"\n"
         ;;
       ( *[!0-9A-Fa-f]* ) 
-      	echo "Not a valid hex value"
-      	printf "If you would like to start at a specific MAC, enter the final\n2-digit hex value (octet) here. (This is useful if you have terminated\nthe script and wish to pick up where you left off) Otherwise, just hit return.\n"
-      	read startPoint
+      	printf "\n\nNot a valid hex value"
+      	printf "\nIf you would like to start at a specific MAC, enter the final\n2-digit hex value (octet) here. (This is useful if you have terminated\nthe script and wish to pick up where you left off) Otherwise, just hit return.\n"
+      	read -n2 startPoint
       	testForHex
       	;;
       ( * )                
@@ -170,12 +174,12 @@ function testForHex {					#	Makes sure $startPoint is a valid octet
         2)
         	endHex=$startPoint
         	endHex=$((0x${endHex}))
-        	printf "Starting at "$MAC$startPoint"\n"
+        	printf "\n\nStarting at "$MAC$startPoint"\n"
         	;;
         *)
         	echo "Please make sure the value is two digits exactly."
       		printf "If you would like to start at a specific MAC, enter the final\n2-digit hex value (octet) here. (This is useful if you have terminated\nthe script and wish to pick up where you left off) Otherwise, just hit return.\n"
-      		read startPoint
+      		read -n2 startPoint
       		testForHex
       		;;
       	esac
@@ -202,6 +206,7 @@ function setHex {
 		hex=$(printf "%02x" $endHex)	#	Converts the 6th MAC octet to hex
 		endHex=$((endHex + 1))			#	Increment the 6th MAC octet
 		finalMAC=$MAC$hex				#	Concat the 6th octet to the first 5
+		defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist StartOctet -data $hex
 		spoofMAC						#	Run the spoofing function
 	done
 
@@ -220,27 +225,31 @@ function setHex {
 function includeNintendo {
 
 	printf "Would you like to include the Nintendo World MACs in the cycle? Y or N\n"
-	read nintendoMACS					#	Find out if user wants to include Nintendo
+	read -n1 nintendoMACS					#	Find out if user wants to include Nintendo
 										#	World MACs in the cycle
 	case $nintendoMACS in
 		y*)
-			printf "Including Nintendo World MACs.\n\n"
+			printf "\n\nIncluding Nintendo World MACs.\n\n"
 			includeNW=1
+			defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist IncludeNintendoWorld -bool TRUE
 			;;
 		Y*)
-			printf "Including Nintendo World MACs.\n\n"
+			printf "\n\nIncluding Nintendo World MACs.\n\n"
 			includeNW=1
+			defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist IncludeNintendoWorld -bool TRUE
 			;;
 		n*)
-			printf "Omitting Nintendo World MACs.\n\n"
+			printf "\n\nOmitting Nintendo World MACs.\n\n"
 			includeNW=0
+			defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist IncludeNintendoWorld -bool FALSE
 			;;
 		N*)
-			printf "Omitting Nintendo World MACs.\n\n"
+			printf "\n\nOmitting Nintendo World MACs.\n\n"
 			includeNW=0
+			defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist IncludeNintendoWorld -bool FALSE
 			;;
 		*)
-			printf "Please type either Y or N.\n\n"
+			printf "\n\nPlease type either Y or N.\n\n"
 			includeNintendo
 			;;
 	esac
@@ -254,7 +263,7 @@ echo "We need to make sure we are broadcasting using the 'attwifi' SSID."
 
 cp /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist /Library/Preferences/SystemConfiguration/xzone.preferences.plist.bak
 
-defaults write /Library/Preferences/SystemConfiguration/com.apple.airport.preferences InternetSharing -dict-add SSID -data $ssid[01]
+defaults write /Library/Preferences/SystemConfiguration/com.apple.airport.preferences InternetSharing -dict-add SSID -data $ssid[1]
 
 echo "SSID set to 'attwifi'."
 
@@ -322,9 +331,10 @@ function scriptStart {
 		setStartOctet							#	Determine starting octet for MAC
 
 		setSSID									#	Determine which SSID to use
-		
-		printf "\nScript Starting!\n\n"
+
 	fi
+
+	printf "\nScript Starting!\n\n"
 	
 	setHex
 
@@ -346,13 +356,15 @@ else
 	printf "Cycle value too low. Using default cycle of 2 minutes.\n\n"
 fi
 
+defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist CycleFrequency -int $sleepTime
+
 }
 
 function setStartOctet {
 
 printf "\nIf you would like to start at a specific MAC, enter the final\n2-digit hex value (octet) here. (This is useful if you have terminated\nthe script and wish to pick up where you left off) Otherwise, just hit return.\n"
 
-read startPoint							#	Get starting point from user
+read -n2 startPoint						#	Get starting point from user
 
 testForHex								#	Make sure user entered a valid 2 digit octet
 
@@ -364,14 +376,14 @@ cp /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist 
 
 printf "\nWhich SSID would you like to use?\n1. attwifi		2. NZ@McD1		3. (More ...)\n"
 
-read getSSID
+read -n1 getSSID
 
 case $getSSID in
 	1)
-		gotssid=${ssid[01]}					#	attwifi SSID
+		gotssid=${ssid[1]}					#	attwifi SSID
 		;;
 	2)
-		gotssid=${ssid[03]}					#	NZ@McD1 SSID
+		gotssid=${ssid[3]}					#	NZ@McD1 SSID
 		;;
 	3)
 		#	Allow selecting from all SSIDs
@@ -379,20 +391,22 @@ case $getSSID in
 		printf "1. attwifi		2. McDonalds Free WiFi	3. NZ@McD1	\n\n4. NZ@McD2		5. wifine		6. FREESPOT	\n\n7. noasp1		8. noasp2		9. Boingo Hotspot	\n\n10. boingo hotspot	11. ATL-Wi-Fi		12. Toronto Pearson Wi-Fi	\n\n13. AWG-WiFi		14. CLTNET		15. IND_PUBLIC_WiFi	\n\n16. LAX-WiFi		17. MIA-WiFi		18. RDU_WiFi	\n\n19. San.Diego.Airport.Free.WIFI			20. flysacramento	\n\n21. hotspot_Bell	22. BELLWIFI@MCDONALDS	23. Boulevard Saint-Laurent WIFI	\n\n"
 		read -p "Press any key to continue... " -n1 -s
 		printf "\n\n24. NintendoSpotPass1	25. NintendoSpotPass2	26. Nintendo_Zone1	\n\n27. Guglielmo		28. Guglielmo_Euronics	29. KPN	\n\n30. METEOR		31. MCDONALDS		32. CASINO_by_METEOR	\n\n33. WiFi Zone - The Cloud			34. mycloud	\n\n35. WLAN Zone - The Cloud			36. mycloud City WiFi	\n\n37. _The Cloud		38. free-hotspot.com	39. hotspot-gratuit.com	\n\n40. Autogrill_Free_WiFi	41. Autogrill Free WiFi	42. Quick WiFi	\n\n43. Quick Wi-Fi		44. Quick_WiFi		45. O2 Wifi	\n\n46. GOWEX FREE WiFi	\n\nPlease type the number of the SSID you wish to use:	"
-		read getSSID
+		read -n2 getSSID
 		while [ $getSSID -gt 46 ]; do
-			echo "You have made an invalid selection. Please try again."
-			read getSSID
+			printf "\n\nYou have made an invalid selection. Please try again."
+			read -n2 getSSID
 		done
 		gotssid=${ssid[$getSSID]}
 		;;
 	*)
-		printf "Please type either 1, 2, or 3\n"
+		printf "\n\nPlease type either 1, 2, or 3\n"
 		setSSID
 		;;
 esac
 
 defaults write /Library/Preferences/SystemConfiguration/com.apple.airport.preferences InternetSharing -dict-add SSID -data $gotssid
+
+defaults write ~/Library/Preferences/com.scytheri0n.xzone.plist SSID -data $gotssid
 
 ssidName=$(echo $gotssid | xxd -r -p)
 
@@ -417,7 +431,7 @@ sleep 1
 sudo ifconfig en1 up
 
 echo "MAC address reverted."
-printf "\n\nThanks for using XZone!"
+printf "\n\nThanks for using XZone!\n\n"
 return 0
 
 }
@@ -430,9 +444,70 @@ exit $?
 
 }
 
+function checkPrefs {
+
+if [ -e ~/Library/Preferences/com.scytheri0n.xzone.plist ]; then
+	isFirstPass=0
+	
+	cp /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist.bak
+	
+	includeNW=$(defaults read ~/Library/Preferences/com.scytheri0n.xzone.plist IncludeNintendoWorld)
+	
+	sleepTime=$(defaults read ~/Library/Preferences/com.scytheri0n.xzone.plist CycleFrequency)
+	
+	hex=$(defaults read ~/Library/Preferences/com.scytheri0n.xzone.plist StartOctet)
+	hex2=${hex#"<"}
+	hex2=${hex2%">"}
+	endHex=$((0x${hex2}))
+	
+	gotssid=$(defaults read ~/Library/Preferences/com.scytheri0n.xzone.plist SSID)
+	ssid2=${gotssid#"<"}
+	ssid2=${ssid2%">"}
+	ssid2=$(echo -e "$ssid2" | tr -d '[[:space:]]')
+	defaults write /Library/Preferences/SystemConfiguration/com.apple.airport.preferences InternetSharing -dict-add SSID -data $ssid2
+fi
+
+}
+
+function usage {
+
+printf "Usage:	xzone -[h][r][s][v]\nOptions:\n	-h	Help. Displays this help message.\n	-r	Reset. Resets saved preferences.\n	-s	Silent. Runs the program silently.\n	-v	Verbose. Logs output to stdout. This is the default\n		option if no options are passed.\n\n"
+exit $?
+
+}
+
 #########################################################################################
 
-clear									#	Clears the terminal window
+while getopts hrsv option
+do
+case $option in
+	v)
+		echo "Running verbose. All output will be displayed."
+		;;
+	s)
+		if [ -e ~/Library/Preferences/com.scytheri0n.xzone.plist ]; then
+			exec 1>/dev/null 2>&1
+		else
+			echo "No preferences exist. Script cannot be run silently without preferences."
+		fi
+		;;
+	h)
+		usage
+		exit 1
+		;;
+	r)
+		if [ -e ~/Library/Preferences/com.scytheri0n.xzone.plist ]; then
+			sudo rm ~/Library/Preferences/com.scytheri0n.xzone.plist
+		else
+			echo "No preferences exist so there's nothing to reset. Silly!"
+		fi
+		;;
+	*)
+		usage
+		exit 1
+		;;
+esac
+done
 
 #	We need to check if we are running as root to execute some of the commands.
 if [ $UID != 0 ]; then
@@ -443,9 +518,11 @@ if [ $UID != 0 ]; then
     
 fi
 
-echo "Running as root. Proceeding."
-
+clear									#	Clears the terminal window
+	
 trap scriptAbort SIGINT SIGTERM
+
+checkPrefs								#	Check for and set preferences
 
 scriptStart								#	Start running the script proper
 
